In [17]:
import sympy as sym
import numpy as np
import cmath

In [18]:
Gamma0=np.array([[0 , 0, 1, 0], [0, 0, 0, 1], [1, 0, 0, 0], [0, 1, 0, 0]])
Gamma0

array([[0, 0, 1, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 1, 0, 0]])

In [19]:
Gamma1 = np.array([[0, 0, 0, 1], [0, 0, 1, 0], [0, 1, 0, 0], [1, 0, 0, 0]])
Gamma1

array([[0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0]])

In [20]:
Gamma2 =np.array([[0, 0, 0, -1j], [0, 0, 1j, 0], [0, -1j, 0, 0], [1j, 0, 0, 0]])
Gamma2

array([[ 0.+0.j,  0.+0.j,  0.+0.j, -0.-1.j],
       [ 0.+0.j,  0.+0.j,  0.+1.j,  0.+0.j],
       [ 0.+0.j, -0.-1.j,  0.+0.j,  0.+0.j],
       [ 0.+1.j,  0.+0.j,  0.+0.j,  0.+0.j]])

In [21]:
Gamma3 = np.array([[0, 0, 1, 0], [0, 0, 0, -1], [1, 0, 0, 0], [0, -1, 0, 0]])
Gamma2

array([[ 0.+0.j,  0.+0.j,  0.+0.j, -0.-1.j],
       [ 0.+0.j,  0.+0.j,  0.+1.j,  0.+0.j],
       [ 0.+0.j, -0.-1.j,  0.+0.j,  0.+0.j],
       [ 0.+1.j,  0.+0.j,  0.+0.j,  0.+0.j]])

In [22]:
Gamma=np.array([Gamma0,Gamma1,Gamma2,Gamma3])

In [86]:
C=np.dot(Gamma3,Gamma1)

In [87]:
C

array([[ 0,  1,  0,  0],
       [-1,  0,  0,  0],
       [ 0,  0,  0,  1],
       [ 0,  0, -1,  0]])

In [24]:
type(Gamma0)

numpy.ndarray

In [25]:
np.matmul(Gamma0,Gamma1)

array([[0, 1, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0]])

In [26]:
Gamma0*Gamma1

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [27]:
np.dot(Gamma0,Gamma1)

array([[0, 1, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0]])

In [28]:
Gamma2*1j

array([[ 0.+0.j,  0.+0.j,  0.+0.j,  1.-0.j],
       [ 0.+0.j,  0.+0.j, -1.+0.j,  0.+0.j],
       [ 0.+0.j,  1.-0.j,  0.+0.j,  0.+0.j],
       [-1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j]])

In [29]:
Gamma2

array([[ 0.+0.j,  0.+0.j,  0.+0.j, -0.-1.j],
       [ 0.+0.j,  0.+0.j,  0.+1.j,  0.+0.j],
       [ 0.+0.j, -0.-1.j,  0.+0.j,  0.+0.j],
       [ 0.+1.j,  0.+0.j,  0.+0.j,  0.+0.j]])

In [30]:
Gamma[0].shape

(4, 4)

In [31]:
np.zeros(Gamma[0].shape)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
for i in range(1,len(Gamma)):
    print(i)

1
2
3


In [33]:
m=(1j)**2
m*Gamma2

array([[-0.+0.j, -0.+0.j, -0.+0.j,  0.+1.j],
       [-0.+0.j, -0.+0.j, -0.-1.j, -0.+0.j],
       [-0.+0.j,  0.+1.j, -0.+0.j, -0.+0.j],
       [-0.-1.j, -0.+0.j, -0.+0.j, -0.+0.j]])

In [34]:
def GammaStar(Gamma):
    Matmul=0
    C=Gamma[0]
    for i in range(1,len(Gamma)):
        C=np.dot(C,Gamma[i])
    return C*(1j)**(len(Gamma)/2 +1)

    

In [67]:
Y=sympy.symbols("m")
y=sympy.symbols("H")

In [73]:
def symbol_isupper(x):
    x_string=str(x.name)
    return x_string.isupper()
def symbol_upper(x):
    x_string=str(x.name).upper()
    return sympy.symbols(x_string)
def symbol_lower(x):
    x_string=str(x.name).lower()
    return sympy.symbols(x_string)

In [74]:
c=sympy.symbols("c",complex=True)

In [77]:
sympy.re(c)

re(c)

In [79]:
x,y=sympy.symbols("x,Y")

In [95]:
T=np.array([x,y,1]).reshape(-1,1)

In [97]:
T[0]

array([x], dtype=object)

In [84]:
T.transpose()

array([[x, 1],
       [Y, 0],
       [1, x]], dtype=object)

In [85]:
np.dot(Gamma3,Gamma1)

array([[ 0,  1,  0,  0],
       [-1,  0,  0,  0],
       [ 0,  0,  0,  1],
       [ 0,  0, -1,  0]])

In [88]:
def Bar_four(V,complex=True):
    if complex=True:
        
        V_bar=1j*V.transpose()
    return np.dot(V_bar,C)

In [ ]:
def Conjugate(x):
    

In [136]:
#a,A,b,B=sympy.symbols("a A b B")
V=np.array([a +1 ,A+2,b+ 4j,-B]).reshape(-1,1)
V

array([[a + 1],
       [A + 2],
       [b + 4.0*I],
       [-B]], dtype=object)

In [105]:
Bar_four(V)

array([[-1.0*I*(A + 2), 1.0*I*(a + 1), 1.0*I*B, 1.0*I*(b + 4.0*I)]],
      dtype=object)

In [108]:
V

array([[a + 1],
       [A + 2],
       [b + 4.0*I],
       [-B]], dtype=object)

In [137]:
len(V)

4

In [138]:
V[2].real

array([b + 4.0*I], dtype=object)

In [127]:
t=sympy.Symbol("t",real=True)
sympy.im(t+3j)

3.00000000000000

In [133]:
i=t+3j
type(i)

sympy.core.add.Add

In [134]:
i=V[2]
type(i)

numpy.ndarray

In [151]:
x=sympy.Symbol("x")
A=sympy.Matrix([[x,1,1,1],[0,0,1,1j +x],[x,1,1,1],[0,0,1,1j +x]])

In [152]:
A


Matrix([
[x, 1, 1,         1],
[0, 0, 1, x + 1.0*I],
[x, 1, 1,         1],
[0, 0, 1, x + 1.0*I]])

In [153]:
A[0,0]

x

In [155]:
Gamma0

array([[0, 0, 1, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 1, 0, 0]])

In [154]:
np.dot(A,Gamma0)

array([[1, 1, x, 1],
       [1, x + 1.0*I, 0, 0],
       [1, 1, x, 1],
       [1, x + 1.0*I, 0, 0]], dtype=object)