In [18]:
import sympy
import numpy as np
import cmath

In [45]:
Gamma0=np.array([[0 , 0, 1, 0], [0, 0, 0, 1], [1, 0, 0, 0], [0, 1, 0, 0]])
Gamma0

array([[0, 0, 1, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 1, 0, 0]])

In [47]:
Gamma1 = np.array([[0, 0, 0, 1], [0, 0, 1, 0], [0, 1, 0, 0], [1, 0, 0, 0]])
Gamma1

array([[0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0]])

In [65]:
Gamma2 =np.array([[0, 0, 0, -1j], [0, 0, 1j, 0], [0, -1j, 0, 0], [1j, 0, 0, 0]])
Gamma2

array([[ 0.+0.j,  0.+0.j,  0.+0.j, -0.-1.j],
       [ 0.+0.j,  0.+0.j,  0.+1.j,  0.+0.j],
       [ 0.+0.j, -0.-1.j,  0.+0.j,  0.+0.j],
       [ 0.+1.j,  0.+0.j,  0.+0.j,  0.+0.j]])

In [68]:
Gamma3 = np.array([[0, 0, 1, 0], [0, 0, 0, -1], [1, 0, 0, 0], [0, -1, 0, 0]])
Gamma2

array([[ 0.+0.j,  0.+0.j,  0.+0.j, -0.-1.j],
       [ 0.+0.j,  0.+0.j,  0.+1.j,  0.+0.j],
       [ 0.+0.j, -0.-1.j,  0.+0.j,  0.+0.j],
       [ 0.+1.j,  0.+0.j,  0.+0.j,  0.+0.j]])

In [69]:
Gamma=np.array([Gamma0,Gamma1,Gamma2,Gamma3])

In [71]:
len(Gamma)

4

In [50]:
type(Gamma0)

numpy.ndarray

In [51]:
np.matmul(Gamma0,Gamma1)

array([[0, 1, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0]])

In [54]:
Gamma0*Gamma1

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [55]:
np.dot(Gamma0,Gamma1)

array([[0, 1, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0]])

In [67]:
Gamma2*1j

array([[ 0.+0.j,  0.+0.j,  0.+0.j,  1.-0.j],
       [ 0.+0.j,  0.+0.j, -1.+0.j,  0.+0.j],
       [ 0.+0.j,  1.-0.j,  0.+0.j,  0.+0.j],
       [-1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j]])

In [66]:
Gamma2

array([[ 0.+0.j,  0.+0.j,  0.+0.j, -0.-1.j],
       [ 0.+0.j,  0.+0.j,  0.+1.j,  0.+0.j],
       [ 0.+0.j, -0.-1.j,  0.+0.j,  0.+0.j],
       [ 0.+1.j,  0.+0.j,  0.+0.j,  0.+0.j]])

In [75]:
m

(-1+0j)

In [77]:
Gamma[0].shape

(4, 4)

In [78]:
np.zeros(Gamma[0].shape)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [79]:
for i in range(1,len(Gamma)):
    print(i)

1
2
3


In [74]:
m=(1j)**2
m*Gamma2

array([[-0.+0.j, -0.+0.j, -0.+0.j,  0.+1.j],
       [-0.+0.j, -0.+0.j, -0.-1.j, -0.+0.j],
       [-0.+0.j,  0.+1.j, -0.+0.j, -0.+0.j],
       [-0.-1.j, -0.+0.j, -0.+0.j, -0.+0.j]])

In [82]:
def GammaStar(Gamma):
    Matmul=0
    C=Gamma[0]
    for i in range(1,len(Gamma)):
        C=np.dot(C,Gamma[i])
    return C*(1j)**(len(Gamma)/2 +1)

    

In [ ]:
def Bar_four(V):
    

In [83]:
GammaStar(Gamma)

array([[1.-0.j, 0.-0.j, 0.-0.j, 0.-0.j],
       [0.-0.j, 1.-0.j, 0.-0.j, 0.-0.j],
       [0.-0.j, 0.-0.j, 1.-0.j, 0.-0.j],
       [0.-0.j, 0.-0.j, 0.-0.j, 1.-0.j]])