In [1]:
import sympy as sym
import numpy as np
import cmath
from sympy import I
from sympy.physics.quantum import TensorProduct

In [49]:
import sys

In [50]:
import subprocess

In [2]:
#####
#Gamma0=sym.Matrix([[0 , 0, 1, 0], [0, 0, 0, 1], [-1, 0, 0, 0], [0, -1, 0, 0]])
#Gamma1 = sym.Matrix([[0, 0, 0, 1], [0, 0, 1, 0], [0, 1, 0, 0], [1, 0, 0, 0]])
#Gamma2 =sym.Matrix([[0, 0, 0, -1*I], [0, 0, 1*I, 0], [0, -1*I, 0, 0], [1*I, 0, 0, 0]])
#Gamma3 = sym.Matrix([[0, 0, 1, 0], [0, 0, 0, -1], [1, 0, 0, 0], [0, -1, 0, 0]])
#Gamma=[Gamma0,Gamma1,Gamma2,Gamma3]

In [3]:
sigma1=sym.Matrix([[0,1],[1,0]])
sigma2=sym.Matrix([[0,-I],[I,0]])
sigma3=sym.Matrix([[1,0],[0,-1]])

In [4]:
gamma0=I*sigma3
gamma1=sigma1
gamma2=sigma2
gamma=[gamma0,gamma1,gamma2]

In [5]:
Gamma0=TensorProduct(I*sigma2,sym.eye(sigma1.shape[0]))
Gamma1=TensorProduct(sigma1,sigma1)
Gamma2=TensorProduct(sigma1,sigma2)
Gamma3=TensorProduct(sigma1,sigma3)
Gamma=[Gamma0,Gamma1,Gamma2,Gamma3]

In [6]:
Gamma_p=(Gamma0+Gamma3)/sym.sqrt(2)
Gamma_m=(Gamma0-Gamma3)/sym.sqrt(2)

In [7]:
P_p=(sym.eye(Gamma0.shape[0])+Gamma0*Gamma3)/2
P_m=(sym.eye(Gamma0.shape[0])-Gamma0*Gamma3)/2

In [8]:
Eta_mn=sym.Matrix([[0,-1,0,0],[-1,0,0,0],[0,0,1,0],[0,0,0,1]])
eta_mn=sym.Matrix([[-1,0,0],[0,1,0],[0,0,1]])

In [9]:
def GammaStar(Gamma):
    C=Gamma[0]
    for i in range(1,len(Gamma)):
        C=C*Gamma[i]
    return C*(-I)**int(len(Gamma)/2 +1)

In [10]:
def symbol_isupper(x):
    x_string=str(x)
    return x_string.isupper()
def symbol_upper(x):
    x_string=str(x).upper()
    return sym.symbols(x_string)
def symbol_lower(x):
    x_string=str(x).lower()
    return sym.symbols(x_string)

In [11]:
def Bar_4(V):
    V=V.transpose()
    return I*V*(Gamma3*Gamma1)

In [12]:
def Bar_3(V):
    V=V.transpose()
    return I*V*sigma2

In [13]:
def Parser(x):
    if x.shape==(4,1):
        x_out=sym.Matrix.zeros(2,1)
        i=0
        for j in range(len(x)):
            if x[j]!=0:
                x_out[i]=x[j]
                i+=1
    elif x.shape==(1,4):
        x_out=sym.Matrix.zeros(1,2)
        i=0
        for j in range(len(x)):
            if x[j]!=0:
                x_out[i]=x[j]
                i+=1
    return x_out

In [23]:
e_p=sym.Symbol("epsilon_+")
e_m=sym.Symbol("epsilon_-")
e_p=Parser(P_p*e)
e_m=I*gamma1*Parser(P_m*e)

In [30]:
l_p,l_m=sym.symbols("lambda_+,lambda_-")
l_p,l_m=Parser(P_p*l),I*gamma1*Parser(P_m*l)


Matrix([
[            lambda_0],
[-conjugate(lambda_0)]])

In [24]:
e_m

Matrix([
[I*conjugate(epsilon_1)],
[           I*epsilon_1]])

In [25]:
e_p

Matrix([
[            epsilon_0],
[-conjugate(epsilon_0)]])

In [80]:
sigma3

Matrix([
[1,  0],
[0, -1]])

In [77]:
gamma2

Matrix([
[0, -I],
[I,  0]])

In [76]:
Gamma2

Matrix([
[0,  0, 0, -I],
[0,  0, I,  0],
[0, -I, 0,  0],
[I,  0, 0,  0]])

In [14]:
x=sym.Symbol("x")
test_v=sym.Matrix([x,-x.conjugate()])

In [15]:
Eta_mn=sym.Matrix([[0,-1,0,0],[-1,0,0,0],[0,0,1,0],[0,0,0,1]])
eta_mn=sym.Matrix([[-1,0,0],[0,1,0],[0,0,1]])
eta_mn

Matrix([
[-1, 0, 0],
[ 0, 1, 0],
[ 0, 0, 1]])

In [16]:
GammaStar(Gamma)

Matrix([
[-1,  0, 0, 0],
[ 0, -1, 0, 0],
[ 0,  0, 1, 0],
[ 0,  0, 0, 1]])

In [17]:
P_p*GammaStar(Gamma)

Matrix([
[-1, 0, 0, 0],
[ 0, 0, 0, 0],
[ 0, 0, 0, 0],
[ 0, 0, 0, 1]])

In [14]:
a,b=sym.symbols("epsilon_0,epsilon_1")
x,y=sym.symbols("lambda_0,lambda_1")
e=sym.Matrix([a,b,b.conjugate(),-a.conjugate()])
l=sym.Matrix([x,y,y.conjugate(),-x.conjugate()])

In [22]:
x.conjugate()

conjugate(lambda_0)

In [23]:
Bar_4(e)

Matrix([[-I*epsilon_1, I*epsilon_0, I*conjugate(epsilon_0), I*conjugate(epsilon_1)]])

In [48]:
f=sym.Matrix.zeros(4,1)
for i in range(len(f)):
    if f[i]==0:
        print("y")

y
y
y
y


In [47]:
f

Matrix([
[            epsilon_0],
[            epsilon_1],
[ conjugate(epsilon_1)],
[-conjugate(epsilon_0)]])

In [ ]:
for i in range(len(e))

In [59]:
def Parser(x):
    if x.shape==(4,1):
        x_out=sym.Matrix.zeros(2,1)
        i=0
        for j in range(len(x)):
            if x[j]!=0:
                x_out[i]=x[j]
                i+=1
    elif x.shape==(1,4):
        x_out=sym.Matrix.zeros(1,2)
        i=0
        for j in range(len(x)):
            if x[j]!=0:
                x_out[i]=x[j]
                i+=1
    return x_out



        

In [55]:
for i in range(len(e)):
    if e[i]!=0:
        print("y")
        print(e[i])

y
epsilon_0
y
epsilon_1
y
conjugate(epsilon_1)
y
-conjugate(epsilon_0)


In [71]:
e_p=P_p*e
e_p

Matrix([
[            epsilon_0],
[                    0],
[                    0],
[-conjugate(epsilon_0)]])

In [72]:
e_p.shape

(4, 1)

In [75]:
Parser(e_p)

Matrix([[epsilon_0, -conjugate(epsilon_0)]])

In [73]:
e_p=e_p.transpose()

In [74]:
e_p.shape

(1, 4)

In [64]:
Parser(e_p)

AttributeError: 'function' object has no attribute 'shape'

In [31]:
if e.transpose().shape==(4,1):print("y")
else:print("n")

n


In [36]:
v1=Bar_4(e)*Gamma_p*l

In [56]:
Eta_mn

Matrix([
[ 0, -1, 0, 0],
[-1,  0, 0, 0],
[ 0,  0, 1, 0],
[ 0,  0, 0, 1]])

In [59]:
sym.eye(4)

Matrix([
[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0],
[0, 0, 0, 1]])

In [58]:
Eta_mn[2,3]

0

In [71]:
def Gamma_ij(i,j):
    ##2\eta^{\mu \nu}=\gamma^{\mu}\gamma^{\nu}+\gamma^{\nu}\gamma^{\mu}
    ##2\gamma^{\mu \nu}=\gamma^{\mu}\gamma^{\nu}-\gamma^{\nu}\gamma^{\mu}
    Gamma_ij=Gamma[i]*Gamma[j]-Eta_mn[i,j]*sym.eye(4)
    return Gamma_ij

In [65]:
def gamma_ij(i,j):
    ##2\eta^{\mu \nu}=\gamma^{\mu}\gamma^{\nu}+\gamma^{\nu}\gamma^{\mu}
    ##2\gamma^{\mu \nu}=\gamma^{\mu}\gamma^{\nu}-\gamma^{\nu}\gamma^{\mu}
    gamma_ij=gamma[i]*gamma[j]-eta_mn[i,j]*sym.eye(2)
    return gamma_ij

In [76]:
Gamma_ij(3,2)

Matrix([
[ 0, -I,  0,  0],
[-I,  0,  0,  0],
[ 0,  0,  0, -I],
[ 0,  0, -I,  0]])

In [67]:
gamma_ij(0,1)

Matrix([
[ 0, I],
[-I, 0]])

In [62]:
Gamma[0]

Matrix([
[ 0,  0, 1, 0],
[ 0,  0, 0, 1],
[-1,  0, 0, 0],
[ 0, -1, 0, 0]])

In [63]:
Gamma[1]

Matrix([
[0, 0, 0, 1],
[0, 0, 1, 0],
[0, 1, 0, 0],
[1, 0, 0, 0]])

In [64]:
Eta_mn[0,1]

-1

In [53]:
gamma0.shape[1]

2

In [38]:
e_m

Matrix([
[I*conjugate(epsilon_1)],
[           I*epsilon_1]])

In [39]:
bar_e_m=Bar_3(e_m)

Matrix([[-I*epsilon_1, I*conjugate(epsilon_1)]])

In [41]:
l_m

Matrix([
[I*conjugate(lambda_1)],
[           I*lambda_1]])

In [42]:
v1

Matrix([[-sqrt(2)*I*epsilon_1*conjugate(lambda_1) - sqrt(2)*I*lambda_1*conjugate(epsilon_1)]])

In [45]:
test2=Bar_3(e_m)*gamma0*l_m

In [46]:
test2

Matrix([[I*epsilon_1*conjugate(lambda_1) + I*lambda_1*conjugate(epsilon_1)]])

In [239]:
new_test_v=test_v.transpose()
new_test_v

Matrix([[x, conjugate(x)]])

In [241]:
I*new_test_v*sigma2

Matrix([[-conjugate(x), x]])

In [246]:
Bar_3(test_v)

Matrix([[conjugate(x), x]])

In [48]:
sym.simplify(v1)

Matrix([[sqrt(2)*I*(-epsilon_1*conjugate(lambda_1) - lambda_1*conjugate(epsilon_1))]])

In [66]:
Gamma_p=(Gamma0+Gamma3)/sym.sqrt(2)
Gamma_m=(Gamma0-Gamma3)/sym.sqrt(2)

In [67]:
type(Gamma_p)

sympy.matrices.dense.MutableDenseMatrix

In [149]:
a,A,b,B=sym.symbols("a,A,b,B")
test_V=sym.Matrix([a,b,B,-A])
c=sym.Symbol("C",real=True)

In [139]:
test_V=test_V.transpose()

In [150]:
test_V

Matrix([
[ a],
[ b],
[ B],
[-A]])

In [141]:
test_V*Gamma3*Gamma1

Matrix([[-b, a, A, B]])

In [156]:
a,b=sym.symbols("a,b")
test_V=sym.Matrix([a,b,b.conjugate(),-a.conjugate()])

In [157]:
test_V

Matrix([
[            a],
[            b],
[ conjugate(b)],
[-conjugate(a)]])

In [160]:
def Bar_four(V,complex=True):
    V=V.transpose()
    return I*V*(Gamma3*Gamma1)


In [161]:
Bar_four(test_V)

Matrix([[-I*b, I*a, I*conjugate(a), I*conjugate(b)]])

In [144]:
test_V[3]=test_V[1]
test_V[3]

b

In [152]:
x=sym.Symbol("x")
test_m=sym.Matrix([x,x.conjugate()])

In [153]:
test_m

Matrix([
[           x],
[conjugate(x)]])

In [154]:
test_m.conjugate()

Matrix([
[conjugate(x)],
[           x]])

In [147]:
j=symbol_upper(a)
type(j)

sympy.core.symbol.Symbol

In [151]:
Bar_four(test_V)

B
b
-A
-a


Matrix([[A, B, b, -a]])

In [113]:
H=A

In [ ]:
sym.Syo

In [102]:
h=str(H)

In [118]:
if symbol_isupper(hh):
    print("y")

In [104]:
h

'A + 1'

In [114]:
h.isupper()

True

In [115]:
hh=symbol_lower(H)

In [116]:
hh

a

In [95]:
symbol_isupper(H)

AttributeError: 'Add' object has no attribute 'name'

In [18]:
Gamma0=np.array([[0 , 0, 1, 0], [0, 0, 0, 1], [1, 0, 0, 0], [0, 1, 0, 0]])
Gamma0

array([[0, 0, 1, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 1, 0, 0]])

In [19]:
Gamma1 = np.array([[0, 0, 0, 1], [0, 0, 1, 0], [0, 1, 0, 0], [1, 0, 0, 0]])
Gamma1

array([[0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0]])

In [20]:
Gamma2 =np.array([[0, 0, 0, -1j], [0, 0, 1j, 0], [0, -1j, 0, 0], [1j, 0, 0, 0]])
Gamma2

array([[ 0.+0.j,  0.+0.j,  0.+0.j, -0.-1.j],
       [ 0.+0.j,  0.+0.j,  0.+1.j,  0.+0.j],
       [ 0.+0.j, -0.-1.j,  0.+0.j,  0.+0.j],
       [ 0.+1.j,  0.+0.j,  0.+0.j,  0.+0.j]])

In [21]:
Gamma3 = np.array([[0, 0, 1, 0], [0, 0, 0, -1], [1, 0, 0, 0], [0, -1, 0, 0]])
Gamma2

array([[ 0.+0.j,  0.+0.j,  0.+0.j, -0.-1.j],
       [ 0.+0.j,  0.+0.j,  0.+1.j,  0.+0.j],
       [ 0.+0.j, -0.-1.j,  0.+0.j,  0.+0.j],
       [ 0.+1.j,  0.+0.j,  0.+0.j,  0.+0.j]])

In [22]:
Gamma=np.array([Gamma0,Gamma1,Gamma2,Gamma3])

In [86]:
C=np.dot(Gamma3,Gamma1)

In [87]:
C

array([[ 0,  1,  0,  0],
       [-1,  0,  0,  0],
       [ 0,  0,  0,  1],
       [ 0,  0, -1,  0]])

In [24]:
type(Gamma0)

numpy.ndarray

In [25]:
np.matmul(Gamma0,Gamma1)

array([[0, 1, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0]])

In [26]:
Gamma0*Gamma1

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [27]:
np.dot(Gamma0,Gamma1)

array([[0, 1, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0]])

In [28]:
Gamma2*1j

array([[ 0.+0.j,  0.+0.j,  0.+0.j,  1.-0.j],
       [ 0.+0.j,  0.+0.j, -1.+0.j,  0.+0.j],
       [ 0.+0.j,  1.-0.j,  0.+0.j,  0.+0.j],
       [-1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j]])

In [29]:
Gamma2

array([[ 0.+0.j,  0.+0.j,  0.+0.j, -0.-1.j],
       [ 0.+0.j,  0.+0.j,  0.+1.j,  0.+0.j],
       [ 0.+0.j, -0.-1.j,  0.+0.j,  0.+0.j],
       [ 0.+1.j,  0.+0.j,  0.+0.j,  0.+0.j]])

In [30]:
Gamma[0].shape

(4, 4)

In [31]:
np.zeros(Gamma[0].shape)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
for i in range(1,len(Gamma)):
    print(i)

1
2
3


In [33]:
m=(1j)**2
m*Gamma2

array([[-0.+0.j, -0.+0.j, -0.+0.j,  0.+1.j],
       [-0.+0.j, -0.+0.j, -0.-1.j, -0.+0.j],
       [-0.+0.j,  0.+1.j, -0.+0.j, -0.+0.j],
       [-0.-1.j, -0.+0.j, -0.+0.j, -0.+0.j]])

In [34]:
def GammaStar(Gamma):
    Matmul=0
    C=Gamma[0]
    for i in range(1,len(Gamma)):
        C=np.dot(C,Gamma[i])
    return C*(1j)**(len(Gamma)/2 +1)

    

In [67]:
Y=sympy.symbols("m")
y=sympy.symbols("H")

In [73]:
def symbol_isupper(x):
    x_string=str(x.name)
    return x_string.isupper()
def symbol_upper(x):
    x_string=str(x.name).upper()
    return sympy.symbols(x_string)
def symbol_lower(x):
    x_string=str(x.name).lower()
    return sympy.symbols(x_string)

In [74]:
c=sympy.symbols("c",complex=True)

In [77]:
sympy.re(c)

re(c)

In [79]:
x,y=sympy.symbols("x,Y")

In [95]:
T=np.array([x,y,1]).reshape(-1,1)

In [97]:
T[0]

array([x], dtype=object)

In [84]:
T.transpose()

array([[x, 1],
       [Y, 0],
       [1, x]], dtype=object)

In [85]:
np.dot(Gamma3,Gamma1)

array([[ 0,  1,  0,  0],
       [-1,  0,  0,  0],
       [ 0,  0,  0,  1],
       [ 0,  0, -1,  0]])

In [88]:
def Bar_four(V,complex=True):
    if complex=True:
        
        V_bar=1j*V.transpose()
    return np.dot(V_bar,C)

In [ ]:
def Conjugate(x):
    

In [136]:
#a,A,b,B=sympy.symbols("a A b B")
V=np.array([a +1 ,A+2,b+ 4j,-B]).reshape(-1,1)
V

array([[a + 1],
       [A + 2],
       [b + 4.0*I],
       [-B]], dtype=object)

In [105]:
Bar_four(V)

array([[-1.0*I*(A + 2), 1.0*I*(a + 1), 1.0*I*B, 1.0*I*(b + 4.0*I)]],
      dtype=object)

In [108]:
V

array([[a + 1],
       [A + 2],
       [b + 4.0*I],
       [-B]], dtype=object)

In [137]:
len(V)

4

In [138]:
V[2].real

array([b + 4.0*I], dtype=object)

In [127]:
t=sympy.Symbol("t",real=True)
sympy.im(t+3j)

3.00000000000000

In [133]:
i=t+3j
type(i)

sympy.core.add.Add

In [134]:
i=V[2]
type(i)

numpy.ndarray

In [151]:
x=sympy.Symbol("x")
A=sympy.Matrix([[x,1,1,1],[0,0,1,1j +x],[x,1,1,1],[0,0,1,1j +x]])

In [152]:
A


Matrix([
[x, 1, 1,         1],
[0, 0, 1, x + 1.0*I],
[x, 1, 1,         1],
[0, 0, 1, x + 1.0*I]])

In [153]:
A[0,0]

x

In [155]:
Gamma0

array([[0, 0, 1, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 1, 0, 0]])

In [154]:
np.dot(A,Gamma0)

array([[1, 1, x, 1],
       [1, x + 1.0*I, 0, 0],
       [1, 1, x, 1],
       [1, x + 1.0*I, 0, 0]], dtype=object)

In [157]:
H=[A,Gamma0]

In [159]:
H[0]

Matrix([
[x, 1, 1,         1],
[0, 0, 1, x + 1.0*I],
[x, 1, 1,         1],
[0, 0, 1, x + 1.0*I]])

In [77]:
Gamma_ij(1,2)

Matrix([
[I,  0, 0,  0],
[0, -I, 0,  0],
[0,  0, I,  0],
[0,  0, 0, -I]])

In [80]:
Eta_mn.shape[0]

4

In [81]:
for i in range(Eta_mn.shape[0]):
    for j in range(i+1,Eta_mn.shape[0]):
        print("Gamma{}{}".format(i,j))

Gamma01
Gamma02
Gamma03
Gamma12
Gamma13
Gamma23


In [85]:
M=sym.IndexedBase("M")
exp=sym.IndexedBase("exp")
i,j=sym.symbols("i,j")
M[i,j]

M[i, j]

In [90]:
Gamma[0]*M[i,j]

IndexException: 
Range is not defined for all indices in: M[i, j]

In [88]:
for i in range(4):
    for j in range(4):
    Gamma[0]*M[i,j]

IndentationError: expected an indented block (202226463.py, line 3)

In [ ]:
Lorentz = TensorIndexType('Lorentz', dummy_name='L')

mu = TensorIndex('mu', Lorentz, is_up=False)

nu, rho = tensor_indices('nu, rho', Lorentz)

A = TensorHead('A', [Lorentz, Lorentz])

A(mu, nu)
A(-mu, nu)

A(-mu, -rho)
A(mu, -rho)

A(mu, -mu)
A(-L_0, L_0)

In [92]:
from sympy.tensor.tensor import TensorIndexType, TensorIndex, TensorHead, tensor_indices

In [94]:
Lorentz = TensorIndexType('Lorentz', dummy_name='L')
nu, rho = tensor_indices('nu, rho', Lorentz)
A = TensorHead('A', [Lorentz, Lorentz])


In [100]:
from sympy import symbols

Ex, Ey, Ez, Bx, By, Bz = symbols('E_x E_y E_z B_x B_y B_z')

c = symbols('c', positive=True)

In [103]:
from sympy.tensor.tensor import TensorIndexType, TensorHead, TensorSymmetry
asym2 = TensorSymmetry.fully_symmetric(-2)
F = TensorHead('F', [Lorentz, Lorentz], asym2)

In [106]:
repl = {Lorentz: sym.diag(1, -1, -1, -1)}

In [108]:
i0, i1 = tensor_indices('i0:2', Lorentz)

In [109]:
repl.update({F(-i0, -i1): [
[0, Ex/c, Ey/c, Ez/c],
[-Ex/c, 0, -Bz, By],
[-Ey/c, Bz, 0, -Bx],
[-Ez/c, -By, Bx, 0]]})

In [112]:
F(-1,-2)

TypeError: wrong type for index: -1 is <class 'int'>

In [113]:
from sympy import symbols, IndexedBase, Idx
M = IndexedBase('M')
i, j = symbols('i j', cls=Idx)
M[i, j]

M[i, j]

In [114]:
M[1,2]

M[1, 2]

In [116]:
M[1,2]

SyntaxError: invalid syntax (476988579.py, line 1)